"""rework some models

Revision ID: 094bc7fe5bce
Revises: 2ec5d7693b0d
Create Date: 2026-01-11 11:21:41.310815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '094bc7fe5bce'
down_revision: Union[str, Sequence[str], None] = '2ec5d7693b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('album_image', sa.LargeBinary(), nullable=False))
    op.add_column('album', sa.Column('total_tracks', sa.Integer(), nullable=False))
    op.add_column('album', sa.Column('release_year', sa.DateTime(), nullable=False))
    op.add_column('album', sa.Column('image_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('artist', sa.Column('photo', sa.LargeBinary(), nullable=False))
    op.add_column('artist', sa.Column('image_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('artist', sa.Column('monthly_listeners', sa.Integer(), nullable=False))
    op.add_column('track', sa.Column('audio_file', sa.LargeBinary(), nullable=False))
    op.add_column('track', sa.Column('audio_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('track', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('track', sa.Column('audio_size', sa.Integer(), nullable=False))
    op.drop_column('track', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('track', 'audio_size')
    op.drop_column('track', 'created_at')
    op.drop_column('track', 'audio_type')
    op.drop_column('track', 'audio_file')
    op.drop_column('artist', 'monthly_listeners')
    op.drop_column('artist', 'image_type')
    op.drop_column('artist', 'photo')
    op.drop_column('album', 'image_type')
    op.drop_column('album', 'release_year')
    op.drop_column('album', 'total_tracks')
    op.drop_column('album', 'album_image')
    # ### end Alembic commands ###
