"""remake album model

Revision ID: 0bca22738459
Revises: 094bc7fe5bce
Create Date: 2026-01-11 14:43:28.838376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0bca22738459'
down_revision: Union[str, Sequence[str], None] = '094bc7fe5bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('album', sa.Column('album_cover', sa.LargeBinary(), nullable=False))
    op.alter_column('album', 'release_year',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('album', 'album_image')
    op.drop_column('album', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('album', sa.Column('album_image', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.alter_column('album', 'release_year',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('album', 'album_cover')
    op.drop_column('album', 'album_name')
    # ### end Alembic commands ###
