"""Update some models for cascade delete

Revision ID: 216fdf50b18d
Revises: 890aa61c33b3
Create Date: 2026-02-21 12:34:34.458953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216fdf50b18d'
down_revision: Union[str, Sequence[str], None] = '890aa61c33b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('album_artist_id_fkey'), 'album', type_='foreignkey')
    op.create_foreign_key(None, 'album', 'artist', ['artist_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.create_foreign_key(op.f('album_artist_id_fkey'), 'album', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
