"""year release

Revision ID: 34dd1c284bf2
Revises: 0bca22738459
Create Date: 2026-01-11 15:40:21.337561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34dd1c284bf2'
down_revision: Union[str, Sequence[str], None] = '0bca22738459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('year_release', sa.Integer(), nullable=False))
    op.drop_column('album', 'release_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('release_year', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('album', 'year_release')
    # ### end Alembic commands ###
