"""rework track

Revision ID: 4bd0b9f53b35
Revises: 34dd1c284bf2
Create Date: 2026-01-11 21:23:26.107667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4bd0b9f53b35'
down_revision: Union[str, Sequence[str], None] = '34dd1c284bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('track_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('track', sa.Column('duration_sec', sa.Integer(), nullable=False))
    op.drop_column('track', 'name')
    op.drop_column('track', 'duraton_sec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('duraton_sec', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('track', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('track', 'duration_sec')
    op.drop_column('track', 'track_name')
    # ### end Alembic commands ###
