"""update user model

Revision ID: 51137bc2e330
Revises: 3c141d0d3f8d
Create Date: 2026-06-13 11:54:23.234442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51137bc2e330'
down_revision: Union[str, Sequence[str], None] = '3c141d0d3f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums_cover')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums_cover',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('album_cover', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('cover_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('albums_cover_pkey'))
    )
    # ### end Alembic commands ###
