"""updated track model

Revision ID: 59a7b00a3546
Revises: fbf514c0a08f
Create Date: 2026-01-28 17:24:11.127655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a7b00a3546'
down_revision: Union[str, Sequence[str], None] = 'fbf514c0a08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('daily_plays', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('weekly_plays', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('monthly_plays', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('all_time_plays', sa.Integer(), nullable=True))
    op.drop_column('track', 'weekly_listeners')
    op.drop_column('track', 'all_time_listeners')
    op.drop_column('track', 'monthly_listeners')
    op.drop_column('track', 'plays')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('plays', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('track', sa.Column('monthly_listeners', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('track', sa.Column('all_time_listeners', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('track', sa.Column('weekly_listeners', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('track', 'all_time_plays')
    op.drop_column('track', 'monthly_plays')
    op.drop_column('track', 'weekly_plays')
    op.drop_column('track', 'daily_plays')
    # ### end Alembic commands ###
