"""Update album's relethionship

Revision ID: 666ca11e22ba
Revises: 9db683dce95b
Create Date: 2026-04-15 10:38:22.308672

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '666ca11e22ba'
down_revision: Union[str, Sequence[str], None] = '9db683dce95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playevent',
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('duration_listened', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailytop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chart_date', sa.DateTime(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('unique_listeners', sa.Integer(), nullable=False),
    sa.Column('avg_listen_duration', sa.Integer(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('trend', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chart_date', 'track_id', name='uix_daily_track')
    )
    op.create_index('idx_daily_top_date_rank', 'dailytop', ['chart_date', 'rank_position'], unique=False)
    op.create_table('monthlytop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month_start', sa.DateTime(), nullable=False),
    sa.Column('month_end', sa.DateTime(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('unique_listeners', sa.Integer(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_month', 'track_id', name='uix_monthly_track')
    )
    op.create_table('weeklytop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('year_week', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('unique_listeners', sa.Integer(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('trend', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_week', 'track_id', name='uix_weekly_track')
    )
    op.drop_table('populartracks')
    op.add_column('album', sa.Column('cover_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'album', 'albumscover', ['cover_id'], ['id'])
    op.drop_constraint(op.f('albumscover_album_id_fkey'), 'albumscover', type_='foreignkey')
    op.drop_column('albumscover', 'album_id')
    op.alter_column('track', 'daily_plays',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('track', 'weekly_plays',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('track', 'monthly_plays',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('track', 'all_time_plays',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('track', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track', 'all_time_plays',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track', 'monthly_plays',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track', 'weekly_plays',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track', 'daily_plays',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('albumscover', sa.Column('album_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('albumscover_album_id_fkey'), 'albumscover', 'album', ['album_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.drop_column('album', 'cover_id')
    op.create_table('populartracks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('play_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name=op.f('populartracks_track_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('populartracks_pkey'))
    )
    op.drop_table('weeklytop')
    op.drop_table('monthlytop')
    op.drop_index('idx_daily_top_date_rank', table_name='dailytop')
    op.drop_table('dailytop')
    op.drop_table('playevent')
    # ### end Alembic commands ###
