"""cascade delete=true to album relathionship

Revision ID: 682dc78b0bbb
Revises: ffad0440f728
Create Date: 2026-01-12 22:25:53.355007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682dc78b0bbb'
down_revision: Union[str, Sequence[str], None] = 'ffad0440f728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
