"""add tracks qualities

Revision ID: 72ffca6050df
Revises: 682dc78b0bbb
Create Date: 2026-01-14 14:36:41.380133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '72ffca6050df'
down_revision: Union[str, Sequence[str], None] = '682dc78b0bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackhigh',
    sa.Column('audio_file', sa.LargeBinary(), nullable=False),
    sa.Column('audio_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_size', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracklow',
    sa.Column('audio_file', sa.LargeBinary(), nullable=False),
    sa.Column('audio_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_size', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackmedium',
    sa.Column('audio_file', sa.LargeBinary(), nullable=False),
    sa.Column('audio_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_size', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('track', 'audio_type')
    op.drop_column('track', 'audio_file')
    op.drop_column('track', 'audio_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('audio_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('track', sa.Column('audio_file', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('track', sa.Column('audio_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('trackmedium')
    op.drop_table('tracklow')
    op.drop_table('trackhigh')
    # ### end Alembic commands ###
