"""add popularalbums model

Revision ID: 81cea84f9a7e
Revises: a326f11d46bd
Create Date: 2026-03-02 23:24:46.123162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '81cea84f9a7e'
down_revision: Union[str, Sequence[str], None] = 'a326f11d46bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albumscover',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('album_cover', sa.LargeBinary(), nullable=False),
    sa.Column('cover_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('popularalbums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
   

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table('popularalbums')
    op.drop_table('albumscover')
    # ### end Alembic commands ###
