"""Remove artist table, instead add artist and admin profile

Revision ID: 84a71b7e9b41
Revises: 2f458f0ee761
Create Date: 2026-07-06 23:48:08.565210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '84a71b7e9b41'
down_revision: Union[str, Sequence[str], None] = '2f458f0ee761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userrole AS ENUM('guest', 'user', 'artist', 'admin')")

    op.create_table('adminprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('artistprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_listeners', sa.Integer(), nullable=True),
    sa.Column('total_plays', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index(op.f('idx_artist_bio_trgm'), table_name='artist', postgresql_ops={'bio': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_artist_name_trgm'), table_name='artist', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_album_artist_trgm'), table_name='album', postgresql_ops={'artist_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_album_name_trgm'), table_name='album', postgresql_ops={'album_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('album_artist_id_fkey'), 'album', type_='foreignkey')
    op.create_foreign_key(None, 'album', 'artistprofile', ['artist_id'], ['id'], ondelete='CASCADE')
    op.add_column('playlisttrack', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('track', sa.Column('artist_id', sa.Uuid(), nullable=True))
    op.add_column('track', sa.Column('track_low_id', sa.Uuid(), nullable=True))
    op.add_column('track', sa.Column('track_medium_id', sa.Uuid(), nullable=True))
    op.add_column('track', sa.Column('track_high_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('idx_track_artist_trgm'), table_name='track', postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_track_genre_trgm'), table_name='track', postgresql_ops={'genre': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_track_title_trgm'), table_name='track', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_foreign_key(None, 'track', 'tracklow', ['track_low_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'track', 'trackhigh', ['track_high_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'track', 'artistprofile', ['artist_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'track', 'trackmedium', ['track_medium_id'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('has_subscription', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('role', sa.Enum('GUEST', 'USER', 'ARTIST', 'ADMIN', name='userrole'), nullable=False))
    op.add_column('user', sa.Column('avatar_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('liked_albums', sa.JSON(), nullable=True))
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'albums')
    op.drop_table('artist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('albums', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'liked_albums')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'avatar_type')
    op.drop_column('user', 'role')
    op.drop_column('user', 'has_subscription')
    op.drop_column('user', 'username')
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.create_index(op.f('idx_track_title_trgm'), 'track', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_track_genre_trgm'), 'track', ['genre'], unique=False, postgresql_ops={'genre': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_track_artist_trgm'), 'track', ['artist'], unique=False, postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('track', 'track_high_id')
    op.drop_column('track', 'track_medium_id')
    op.drop_column('track', 'track_low_id')
    op.drop_column('track', 'artist_id')
    op.drop_column('playlisttrack', 'order')
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.create_foreign_key(op.f('album_artist_id_fkey'), 'album', 'artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_album_name_trgm'), 'album', ['album_name'], unique=False, postgresql_ops={'album_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_album_artist_trgm'), 'album', ['artist_name'], unique=False, postgresql_ops={'artist_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table('artist',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('image_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monthly_listeners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plays', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('artist_pkey'))
    )
    op.create_index(op.f('idx_artist_name_trgm'), 'artist', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_artist_bio_trgm'), 'artist', ['bio'], unique=False, postgresql_ops={'bio': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table('artistprofile')
    op.drop_table('adminprofile')
    # ### end Alembic commands ###
