"""update album, now play_count default=0

Revision ID: 869c94aaaf7c
Revises: c609986615af
Create Date: 2026-05-01 14:11:13.332433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '869c94aaaf7c'
down_revision: Union[str, Sequence[str], None] = 'c609986615af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('track', 'track_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('track_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('track', 'title')
    # ### end Alembic commands ###
