"""add new table for albums cover

Revision ID: 890aa61c33b3
Revises: e85d4d3aef15
Create Date: 2026-02-21 12:26:37.405999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '890aa61c33b3'
down_revision: Union[str, Sequence[str], None] = 'e85d4d3aef15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums_cover',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('album_cover', sa.LargeBinary(), nullable=False),
    sa.Column('cover_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('album', 'album_cover')
    op.drop_column('album', 'image_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('image_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('album', sa.Column('album_cover', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_table('albums_cover')
    # ### end Alembic commands ###
