"""cover id for album

Revision ID: 994ba40f5279
Revises: 216fdf50b18d
Create Date: 2026-02-21 14:35:10.200802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994ba40f5279'
down_revision: Union[str, Sequence[str], None] = '216fdf50b18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('cover_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'album', 'albums_cover', ['cover_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('albums_cover_album_id_fkey'), 'albums_cover', type_='foreignkey')
    op.drop_column('albums_cover', 'album_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums_cover', sa.Column('album_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('albums_cover_album_id_fkey'), 'albums_cover', 'album', ['album_id'], ['id'])
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.drop_column('album', 'cover_id')
    # ### end Alembic commands ###
