"""rework album model

Revision ID: 9db683dce95b
Revises: 81cea84f9a7e
Create Date: 2026-03-03 23:32:58.888983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db683dce95b'
down_revision: Union[str, Sequence[str], None] = '81cea84f9a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('play_count', sa.Integer(), nullable=False))
    op.drop_column('album', 'cover_id')
    op.add_column('albumscover', sa.Column('album_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'albumscover', 'album', ['album_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albumscover', type_='foreignkey')
    op.drop_column('albumscover', 'album_id')
    op.add_column('album', sa.Column('cover_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('album', 'play_count')
    # ### end Alembic commands ###
