"""album_id is coul be None

Revision ID: c609986615af
Revises: fa1e110058a3
Create Date: 2026-04-18 12:39:51.683537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c609986615af'
down_revision: Union[str, Sequence[str], None] = 'fa1e110058a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'album_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'album_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
