"""update tracks model

Revision ID: da93e9f39791
Revises: b7cff8c821df
Create Date: 2026-01-24 11:07:05.409443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da93e9f39791'
down_revision: Union[str, Sequence[str], None] = 'b7cff8c821df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('plays', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'likes')
    op.drop_column('track', 'plays')
    # ### end Alembic commands ###
