"""updated track model

Revision ID: e1e3a8edcd94
Revises: 72ffca6050df
Create Date: 2026-01-18 23:13:53.225412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e3a8edcd94'
down_revision: Union[str, Sequence[str], None] = '72ffca6050df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('weekly_listeners', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('monthly_listeners', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('all_time_listeners', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'all_time_listeners')
    op.drop_column('track', 'monthly_listeners')
    op.drop_column('track', 'weekly_listeners')
    # ### end Alembic commands ###
