"""Update album

Revision ID: e85d4d3aef15
Revises: eb6419b108f1
Create Date: 2026-02-20 19:56:59.026779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e85d4d3aef15'
down_revision: Union[str, Sequence[str], None] = 'eb6419b108f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.alter_column('track', 'artist',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'artist',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('album', 'artist_name')
    # ### end Alembic commands ###
