"""update track

Revision ID: eb6419b108f1
Revises: 59a7b00a3546
Create Date: 2026-02-15 11:30:16.728648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'eb6419b108f1'
down_revision: Union[str, Sequence[str], None] = '59a7b00a3546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(length=255)))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'artist')
    # ### end Alembic commands ###
