"""genre added to track model

Revision ID: fa1e110058a3
Revises: 666ca11e22ba
Create Date: 2026-04-18 11:22:40.228824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa1e110058a3'
down_revision: Union[str, Sequence[str], None] = '666ca11e22ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('album_cover_id_fkey'), 'album', type_='foreignkey')
    op.create_foreign_key(None, 'album', 'albumscover', ['cover_id'], ['id'], ondelete='CASCADE')
    op.add_column('track', sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'genre')
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.create_foreign_key(op.f('album_cover_id_fkey'), 'album', 'albumscover', ['cover_id'], ['id'])
    # ### end Alembic commands ###
