"""update artist

Revision ID: fbf514c0a08f
Revises: da93e9f39791
Create Date: 2026-01-24 11:44:19.163080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf514c0a08f'
down_revision: Union[str, Sequence[str], None] = 'da93e9f39791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('plays', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('followers', sa.Integer(), nullable=True))
    op.alter_column('artist', 'monthly_listeners',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'monthly_listeners',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('artist', 'followers')
    op.drop_column('artist', 'plays')
    # ### end Alembic commands ###
