"""ondelete=CASCADE in track

Revision ID: ffad0440f728
Revises: cd019b7018ce
Create Date: 2026-01-12 22:14:21.821471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffad0440f728'
down_revision: Union[str, Sequence[str], None] = 'cd019b7018ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('track_album_id_fkey'), 'track', type_='foreignkey')
    op.create_foreign_key(None, 'track', 'album', ['album_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.create_foreign_key(op.f('track_album_id_fkey'), 'track', 'album', ['album_id'], ['id'])
    # ### end Alembic commands ###
